### ISSUE TITLE
Implement a Volume Meter similar to the one in HotKeyP

### ISSUE THREAD

**Issue by Zero3K** [guilryder/clavier-plus#1]
It would be nice if that was done. You can get the program mentioned by going to http://petr.lastovicka.sweb.cz/others.html.

**Comment by guilryder** [comment]
Clavier+ is focused on keyboard handling, not so much on OS user interface features like volume meters. That said, you can use Clavier+ to invoke command-line utilities that control the volume.

**Comment by Zero3K** [comment]
How about if someone else implements it?

**Comment by guilryder** [comment]
Do you mean implementing it in Clavier+?

I would prefer a separate program, to keep Clavier+ focused on what it does best, not reinvent the wheel, and stay compatible across Windows versions. (If I remember correctly, Windows sound APIs changed at some point between WinXP and  Win10, and broke some command-line utilities.) It would also allow people to control the volume with tools other than Clavier+, such as network-based receiver.

**Comment by Zero3K** [comment]
Yes, that is what I meant. Well, it could be an option in its dialog box so that way people won't be forced to see it when muting the volume, etc.

**Comment by Zero3K** [comment]
So, will you implement it or not?
