### ISSUE TITLE
keyboard shortcuts with pressed keys

### ISSUE THREAD

**Issue by slorard** [guilryder/clavier-plus#11]
I want to do the keybindings while i keep pressing the keys, i am trying to use wasd as arrow keys

![image](https://user-images.githubusercontent.com/47602471/110166058-30c4c600-7dca-11eb-9793-2ad3c56ff041.png)

what happens is that I have to stop pressing the keys to use a combination again
when I press it works fine, but if I press again it writes, instead of doing the function it should

**Comment by guilryder** [comment]
Known limitation, not fixable in the general case: https://gryder.org/software/clavier-plus/documentation#limits-repetition
