### ISSUE TITLE
When running Chrome apps, don't open a new windows, but raise the existing one instead

### ISSUE THREAD

**Issue by ztomer** [guilryder/clavier-plus#13]
It's more of a feature request than a bug:
When using Chrome apps as desktop applications (for example, Google Calendar, gmail, etc), using an assigned keyboard shortcut will open a new window on each call.

This does not happen when launching native-ish desktop applications (for example, Whatsapp), hence the expected behavior is to re-use the existing instance.

Using Clavier 11.1.1 on Windows 11

Edit: It may be related to the Chrome App launch command having nothing to do with the application name:
"C:\Program Files (x86)\Google\Chrome\Application\chrome_proxy.exe"  --profile-directory=Default --app-id=kjbdgfilnfhdoflbpgamdcdgpehopbep

Is Google Calendar, for example

**Comment by guilryder** [comment]
This question seems about Chrome, not Clavier+. Once you find a command-line that achieves the desired Chrome behavior ([I cannot help you with that](https://gryder.org/software/clavier-plus/documentation#automate)), configure Clavier+ to execute it.
