### ISSUE TITLE
[Feature Request] Allow to test shortcuts on keyboard when main Window is open

### ISSUE THREAD

**Issue by schmurtzm** [guilryder/clavier-plus#14]
I remark that shortcuts are disabled when the main window of the program is open. 
I see the button "test", it is useful but I think it is more intuitive to test the shortcut that you have just tester directly in real condition (and modify it if necessary).

Do you think possible to keep the shortcuts enabled simultaneously with the main window open ?

(issue probably related with the issue about "Apply" button)

Thank you.

**Comment by guilryder** [comment]
This feature looks impossible to design in a simple and consistent way that works all the time.

The shortcuts may be overlapping with each other (for instance multiple shortcuts associated to the same keystroke) while the configuration window is open. Clavier+ checks for duplicates only when the user clicks "OK", not every time the user makes an edit, to allow temporary situations where there are duplicates.

The "Apply" solution is a compromise that I will discuss in the other issue.
