### ISSUE TITLE
Problem with Power and WakeUp buttons

### ISSUE THREAD

**Issue by forestrf** [guilryder/clavier-plus#2]
The Power and WakeUp buttons of my keyboard are both detected as #255, and when assigned as a shortcut, Supr and they arrow keys also trigger them

Thank you

**Comment by guilryder** [comment]
#255 (0xFF) isn't an [officially supported key code](https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731.aspx), and looks like a special value. It suggests that the keyboard doesn't output standard key codes for Power and WakeUp, but relies on a custom driver to handle these keys. Clavier+ cannot do much about this, unfortunately.
