### ISSUE TITLE
[RFE] Make it easier to enter the selected program when creating a new program shortcut

### ISSUE THREAD

**Issue by claudio-salvio** [guilryder/clavier-plus#22]
Hello @guilryder 

It would be very handy if the selected program could be entered also by typing the program path or pasting it from the clipboard.

Greetings,
Claudio Salvio

**Comment by guilryder** [comment]
It's already supported: *Add* > *Launch Program*, enter the shortcut, then type or copy-paste the program path.

You can also drag & drop the program.
