### ISSUE TITLE
Feature request : Allow Caps Lock + Key for shortcut

### ISSUE THREAD

**Issue by rp1231** [guilryder/clavier-plus#24]
Hi,
I would like to set shortcuts in combination with the Caps Lock key.
For eg. Caps Lock + S to simulate left arrow key.

It would be great if this feature can be implemented.

Thanks

**Comment by guilryder** [comment]
Not possible. Caps Lock isn't a modifier key like Ctrl, Alt, etc. to Clavier+ cannot capture keystrokes like Caps Lock + Key.

**Comment by rp1231** [comment]
Would it be possible if it just detected the pressed state of the caps lock key?

Maybe something like:
Caps Lock(pressed) + S  maps to Left Arrow key

Sorry if this doesn't make sense as I'm not a coder.

**Comment by guilryder** [comment]
No, Clavier+ would need Caps Lock to be a modifier key supported by Windows.

**Comment by rp1231** [comment]
Ok thanks
