### ISSUE TITLE
Feature Request: Minimize to tray and minimize on focus loss

### ISSUE THREAD

**Issue by rp1231** [guilryder/clavier-plus#25]
Hi,

I wanted to make a feature request to add an option to minimize to tray and minimize window on focus loss.

Thanks

**Comment by guilryder** [comment]
What window is this referring to? The Clavier+ configuration window cannot be minimized, only closed, because I cannot think of a good use case for that.

**Comment by guilryder** [comment]
This question seems about Firefox Portable instead of Clavier+. Find a way to achieve what you want (command-line, script, keystrokes, etc.) then configure Clavier+ accordingly -- [FAQ](https://gryder.org/software/clavier-plus/documentation#automate).
