### ISSUE TITLE
Feature request: checkbox to disable/enable existing shortcut

### ISSUE THREAD

**Issue by rp1231** [guilryder/clavier-plus#26]
Hi.

Some times there are situations where the shortcut assigned via clavier+ might be interfering with applications.
At such times it is desirable to disable the shortcut without deleting it permanently.
A check box to disable/ enable an existing shortcut would be handy in such situations.

Thanks

**Comment by guilryder** [comment]
Shortcuts that interfere with some applications should be [edited with the relevant conditions](https://gryder.org/software/clavier-plus/documentation#conditions-active).
