### ISSUE TITLE
Waiting for the finish of the launched program

### ISSUE THREAD

**Issue by cser** [guilryder/clavier-plus#27]
Is there any way to do something exactly after `[[something.bat]]` finished, without very big delays?
(The target is to copy text inside text area to clipboard, processing it by batch file and paste it back after batch processed)

**Comment by guilryder** [comment]
Not natively with Clavier+. Instead, consider adding commands at the end of your *.bat script. You can call Clavier+ from there if useful; see the documentation for details.

**Comment by cser** [comment]
Thanks, `Clavier.exe /sendkeys "[Ctrl+V]"` works in batch!
