### ISSUE TITLE
[Feature Request] Different text output for different condition options

### ISSUE THREAD

**Issue by endo64** [guilryder/clavier-plus#3]
I mostly use Clavier+ for writing out my email address, name and even passwords (I know it is not a good idea) into textboxes etc. But I do have a bunch of web sites & dev projects with different text inputs, hence a bunch of shortcuts.

It would be nice to have different outputs with different conditions for same shortcut key:

```
CTRL-SHIFT-P -> "my-dev-pwd"
CTRL-SHIFT-P -> "my-test-pwd" (scroll lock on)
CTRL-SHIFT-P -> "my-stage-pwd" (caps lock on)
```

**Comment by endo64** [comment]
Nope, it is not supported. You can add only one shortcut key, conditions doesn't make them distinct and gives error when you want to save the config.

Here I have `CTRL-,` for one text and tried to add another one with `capslock` condition and got below error:

![image](https://user-images.githubusercontent.com/840604/52426401-f74bfe80-2b0e-11e9-80f7-c1e0472ff23b.png)

**Comment by guilryder** [comment]
Please read the red warning just above the documentation section I linked to earlier.

**Comment by endo64** [comment]
@guilryder Ah I missed that part, thanks!
