### ISSUE TITLE
last EXE file for NT 5.1 [enhancement]

### ISSUE THREAD

**Issue by andika207** [guilryder/clavier-plus#31]
salut
vous dites que la dernière version pour XP/Vista est **10.8.4**
oui c'est vrai mais uniquement pour le fichier ZIP.
si je veux le fichier EXE je dois utiliser la version **10.8.3** sans les ''Minor fixes''
je veux simplement savoir si vous pouvez résoudre ce petit problème ?

**Comment by guilryder** [comment]
Merci d'avoir signalé ce souci !

L'installeur de la version 10.8.4 utilise une version récente d'Inno Setup incompatible avec Windows XP. J'ai regénéré les installeurs avec une version plus ancienne d'Inno Setup qui devrait fonctionner sous XP :

https://gryder.org/software/clavier-plus/ClavierSetup64_10.8.4.exe
https://gryder.org/software/clavier-plus/ClavierSetup_10.8.4.exe

J'ai besoin de votre aide pour tester car je je n'ai pas de Windows XP sous la main.

**Comment by andika207** [comment]
> J'ai besoin de votre aide pour tester car je je n'ai pas de Windows XP sous la main.

XP n'est par mort du tout... https://xpdelta.weebly.com/
oui ça marche mais le poids fu fichier ne me plaît pas!

**10.8.4 v2** = 579 KB
**10.8.4 v1** = 1463 KB
**10.8.3** = 574 KB

**Comment by guilryder** [comment]
https://github.com/guilryder/clavier-plus/releases/tag/release10.8.4 référence maintenant les nouveaux installeurs.

Je n'ai plus de machine Windows XP depuis longtemps car Microsoft a arrêté le support étendu en 2014. Les failles de sécurité ne sont plus corrigées.

Les installeurs fournis ne sont pas obligatoires. Si la taille de l'installeur est un problème, utilisez le fichier Zip, copiez `Clavier.exe` directement, ou créez votre propre installeur. J'utilise Inno Setup pour générer les installeurs car la configuration est simple. NSIS génèrerait des installeurs plus compacts, mais je ne pense pas que l'investissement en temps en vaille la peine -- et de toute façon je ne regénérerait pas les installeurs des anciennes versions.

**Comment by andika207** [comment]
> Microsoft a arrêté le support étendu en 2014. Les failles de sécurité ne sont plus corrigées.

cette excuse n'est pas valable puisque je demande pas de convertir la version **11.2.1** pour XP 
de toute façon le support officiel a terminé en 2019 et certaines entreprises en profiteront jusqu'à 2025

**Comment by guilryder** [comment]
> bizarre.... ici c'est l'inverse puisque on passe de 1463 vers 579 Mo et je me demande si réellement c'est le même fichier ou si c'est le **10.8.3** avec un numéro différent.

Vous pouvez répondre à cette question sans mon aide, par exemple :
1) Vérifier le numéro de version en cliquant "À propos" dans la fenêtre de configuration de Clavier+.
2) Comparer le `Clavier.exe` copié par l'installeur avec celui du fichier Zip.

En supposant que vous vouliez dire "Ko" au lieu de "Mo", j'imagine que les versions récentes d'Inno Setup génèrent des installeurs plus gros.

> > Microsoft a arrêté le support étendu en 2014. Les failles de sécurité ne sont plus corrigées.
> 
> cette excuse n'est pas valable puisque je demande pas de convertir la version **11.2.1** pour XP de toute façon le support officiel a terminé en 2019 et certaines entreprises en profiteront jusqu'à 2025

Ce n'est pas une excuse, mais une explication du fait que je n'ai pas de Windows XP à ma disposition pour tester les anciennes versions de Clavier+ et de l'installeur. En tant que particulier, plus de mises à jour de sécurité depuis 2014 ([source](https://en.wikipedia.org/wiki/Windows_XP#End_of_support)) ; Windows XP est non seulement obsolète mais aussi dangereux d'utilisation.

**Comment by andika207** [comment]
> j'imagine que les versions récentes d'Inno Setup génèrent des installeurs plus gros.

j'ai rien à dire alors...

**Comment by andika207** [comment]
> En tant que particulier, plus de mises à jour de sécurité depuis 2014 ([source](https://en.wikipedia.org/wiki/Windows_XP#End_of_support)) ; 
Windows XP est non seulement obsolète mais aussi dangereux d'utilisation.

les dernières MIJ datent de 2019 et n' importe quel SO est dangereux si on ne l'utilise pas convenablement
je n' utilise même pas de anti-virus en temps réel et un SO sans télemetrie est bien plus sûr que les autres.
le con de William Gates voulait un SO hybride pour PC et écrans tactiles au lieu d' avoir deux différents
finallement il avait perdu la guerre avec ses Nokia Lumia que personne voulait LOL

**Comment by RamonUnch** [comment]
@andika207 
Désolé de continuer à commenter sur une issue fermée, mais j'ai effectué un build 32bit de clavier: 
https://github.com/RamonUnch/clavier-plus-WinXP/releases
Il devrait fonctionner sus WinXP/2003 et est plus a jour que la version 1.0.8.3
Cependent seulement un zip est disponible.

**Comment by andika207** [comment]
@RamonUnch not sure why you come up with this for me ?
first off your file doesn't match the official 11.2.1 release, yours is still 10.8.4
second I had no issues with the official 10.8.4 ZIP developed by @guilryder 
third your file is 197 KB whereas the official one is 154 KB only
thanks for your input anyway and good luck for the next try.

<a href='https://postimg.cc/Jtd1FKkp' target='_blank'><img src='https://i.postimg.cc/J4RGG24C/ramon.png' border='0' alt='ramon'/></a>
