### ISSUE TITLE
Use %APPDATA%\Clavier\clavier.ini when Running %ProgramFiles%\Clavier\Clavier.exe

### ISSUE THREAD

**Issue by gunnarhaslinger** [guilryder/clavier-plus#32]
We would like to place Clavier.exe in %ProgramFiles%\Clavier\Clavier.exe
In a Multi-User-Setup each user should have it's own Clavier.ini File.
It should e.g. be loaded from %APPDATA%\Clavier\clavier.ini 

How can this be done?

**Comment by guilryder** [comment]
Install Clavier+ in the desired directory, then launch it with [command-line options](https://gryder.org/software/clavier-plus/documentation#cmdline) to load the desired configuration file.

Don't use the built-in "Launch Clavier+ at Windows startup" option, instead configure Windows manually similarly to [what the FAQ says](https://gryder.org/software/clavier-plus/documentation#autostartup).
