### ISSUE TITLE
Make write text more compatible with MS Word

### ISSUE THREAD

**Issue by Stokpan** [guilryder/clavier-plus#33]
When I insert the 𝒪 symbol to Notepad++ using a Write Text shortcut from Clavier+, it gets correctly inserted.

When I paste the 𝒪 symbol to MS Word from Notepad++, it gets correctly inserted.

When I insert the 𝒪 symbol to MS Word using a Write Text shortcut from Clavier+, I get a placeholder square from an asian font.

Would it be possible to have this extremely useful feature working as expected with MS Word ?

**Comment by guilryder** [comment]
It looks like an issue with MS Word, not Clavier+. It's up to you to figure out how to configure MS Word and/or find the keystrokes that Clavier+ can simulate to write text in the desired way ([background](https://gryder.org/software/clavier-plus/documentation#doesnotworkprogram)).
