### ISSUE TITLE
AltGr not reusable after shortcut key input

### ISSUE THREAD

**Issue by L-Yvelin** [guilryder/clavier-plus#36]
I have set the keyboard shortcut "AltGr + ." to input the middle dot character. However, when I try to use AltGr again without releasing it after inputting the middle dot, it does not function, as if it has been released, unless it's a clavier+ shortcut.

Example (US International Keyboard):
    What it does: ·/·
    What it should do: ·¿·
    
    Since "AltGr + /" should return "¿"

I hope I made it clear enough, otherwise don't hesitate to ask for clarification!

**Comment by guilryder** [comment]
Unless I misunderstood the issue, the [documentation](https://gryder.org/software/clavier-plus/documentation#limits-repetition) already covers this in detail.
