### ISSUE TITLE
Feature request: Replace text inside clipboard

### ISSUE THREAD

**Issue by cser** [guilryder/clavier-plus#39]
There is a need to convert formulas from Mathcad to Word and back. It's possible with replacing text in buffer with several regular expressions. Calling external applications for this is very unreliable.
I.e. I want to add something like this to shortcut Ctrl+Shift+C:

    [Ctrl+C][][Replace inside clipboard /\(@LABEL (.*?)\)/$1/g][Replace inside clipboard...

Please make command "Replace text inside clipboard with regex".

**Comment by guilryder** [comment]
This feature looks independent from Clavier+. Write a script that modifies the contents of the clipboard using standard or external utilities. Then configure Clavier+ to call the script from a shortcut. It should be very reliable.

**Comment by cser** [comment]
Okay
