### ISSUE TITLE
[Bug] It doesn't work to press and hold any key

### ISSUE THREAD

**Issue by kin30528** [guilryder/clavier-plus#43]
This software is very great, I've been using it for years. Suddenly, I can't hold press and hold one key with other keys to type the combination of text I want.

For example, I always press and hold key to get the following effect.
<kbd>ctrl</kbd> + <kbd>p</kbd> = ☖
<kbd>ctrl</kbd> + <kbd>p</kbd> + <kbd>p</kbd> = ☖☖

Now
 <kbd>ctrl</kbd> + <kbd>p</kbd> + <kbd>p</kbd> = ☖p

Now to type ☖☖, I must <kbd>ctrl</kbd> + <kbd>p</kbd> and <kbd>ctrl</kbd> + <kbd>p</kbd>
That means I can't press and hold any key. 

I don't know the bug comes from system or software, I hope someone can help me, thanks!

System: Win10 22H2
Software: Clavier+ 11.4.1

**Comment by kin30528** [comment]
> This software is very great, I've been using it for years. Suddenly, I can't hold press and hold one key with other keys to type the combination of text I want.
> 
> For example, I always press and hold key to get the following effect. ctrl + p = ☖ ctrl + p + p = ☖☖
> 
> Now ctrl + p + p = ☖p
> 
> Now to type ☖☖, I must ctrl + p and ctrl + p That means I can't press and hold any key.
> 
> I don't know the bug comes from system or software, I hope someone can help me, thanks!
> 
> System: Win10 22H2 Software: Clavier+ 11.4.1

I uninstalled 11.4.1 and manually deleted \AppData\Local\Clavier+\ Clavier.ini, and then installed 11.2.0 which solved the bug, so I'm almost certain that version 11.4.1 has some bugs.

**Comment by guilryder** [comment]
This is a known limitation, as explained in the [documentation](https://gryder.org/software/clavier-plus/documentation#limits-repetition).
