### ISSUE TITLE
Ctrl + F bug

### ISSUE THREAD

**Issue by snakehill** [guilryder/clavier-plus#44]
Setting any shortcut for `Ctrl + F` makes specifically Google Chrome's Ctrl + F (Find...) not work anymore, even if it's not part of the targeted programs whatsoever.

For example, the following:
```
Shortcut: Ctrl + F
Write text: [Ctrl][Ctrl + F]
Enable for only those programs: photoshop.exe
```
and/or:
```
Shortcut: Ctrl + F
Launch a program: "C:\Program Files\Everything\Everything.exe"
Enable for only those programs: explorer.exe
```

With either one (or both) of those in place, Ctrl + F no longer works in chrome.exe, while it works fine in other browsers (firefox.exe, opera.exe).

This can be fixed by having a specific Ctrl + F entry for chrome.exe or for anything but explorer.exe;photoshop.exe but that obviously shouldn't be needed, else that would mean potentially every single shortcut would need an opposite counterpart.

Since at least 11.4.0 (currently on 11.4.1).

**Comment by guilryder** [comment]
I was unable to reproduce this issue on my computer, so I cannot help. Please reopen this issue if you can confirm it's widespread and not specific to your computer or its configuration.
