### ISSUE TITLE
[Feature Request] Pas de raccourci mais une expression

### ISSUE THREAD

**Issue by pralium444** [guilryder/clavier-plus#46]
Salut ! 

Merci pour ton magnifique logiciel !
Y'a t-il la possibilité d'utiliser des expressions ?
Je sais pas si c'est le bon terme.

Par exemple si j'utilise l'extension chrome ou edge de "Text Blaze", je peux utiliser un "code" comme `/res` pour que cela écrive tout seul :  "En attente de réservation". 
Ce qui m'intéresse c'est d'avoir TextBlaze mais sur n'importe quelle appli. Il n'y a que ton logiciel qui est simple d'accès et qui permet de coller du texte n'importe où sur Windows.
Ce qui facilite la tâche dans mon exemple c'est que "/res" fait référence à "réservation", alors que Maj+Ctrl+0 ou1.2.3 c'est la galère à retenir, surtout si on a plein de phrases différentes à coller.

Bref, je me demandais si c'était possible en l'état actuel (je ne pense pas, j'ai regardé la doc).
Je sais que le slash est un caractère spécial, mais si il y a la possibilité de créér ses propres raccourcis je suis preneur
Voilà, je lance ce caillou à la mer en espérant qu'il arrive à bon port
Merci de ton logiciel encore !
Si tout ceci a été inutile et que la fonction existe déjà et que je suis un boulet, n'hésite pas à me le dire et m'indiquer comment faire comme l'exemple cité ci dessus.
Cordialement, 
Merci a+

**Comment by guilryder** [comment]
Clavier+ ne permet pas de créer de raccourcis associés à plusieurs frappes de touches en séquence comme "/", "r", "e", "s".
