### ISSUE TITLE
Add MULTIUSER_INSTALLMODE_COMMANDLINE flag

### ISSUE THREAD

**Issue by sfonteneau** [guilryder/clavier-plus#47]
Bonjour 

Merci beaucoup pour votre logiciel 

Depuis le passage a NSIS on a perdu la possibilité d'installer le logiciel en mode ALLUSERS

Donc placement dans "Program Files" et uninstallkey dans "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall"

En regardant coter nsis il faudrait utiliser :

MULTIUSER_INSTALLMODE_COMMANDLINE 
https://nsis.sourceforge.io/Docs/MultiUser/Readme.html

Ce serait possible ?

**Comment by guilryder** [comment]
L'installeur est fourni pour le cas simple et courant d'une installation locale. Clavier+ est suffisamment petit qu'installer une copie pour chaque utilisateur est raisonnable. Pour les situations plus compliquées (multi-user, configuration dans un répertoire personnalisé, etc.), installez manuallement.

Complications :
* Installer pour tous les utilisateurs demande des privilèges administrateur.
  * Par défaut NSIS lance Clavier+ à la fin de l'installeur avec les privilèges de l'utilisateur courant, donc administrateur. Pour diverses raisons, c'est une mauvaise idée de lancer Clavier+ avec de tels privilèges.
  * `Clavier.ini` est créé dans le même répertoire que `Clavier.exe`, donc Clavier+ ne peut pas le modifier après installation. Avant NSIS, plein d'utilisateurs se plaignaient de problèmes de permissions ou de `Clavier.ini` perdus. Je ne reçois pratiquement plus de plaintes de ce type maintenant que Clavier+ installe toujours en local.
  * Le désinstalleur a lui aussi besoin de privilèges administrateur.
  * Je veux garder le comportement simple et fiable de l'installeur local.
* Gérer la case "lancer au démarrage de Windows" est difficile dans le cas multi-user. Le comportement attendu n'est pas évident.
* Plusieurs langues n'ont pas de traduction pour les messages dont `MultiUser.nsh` a besoin.

Il serait possible de corriger ces limitations, par exemple en stockant `Clavier.ini` dans un répertoire séparé en mode multi-user, en personnalisant la configuration NSIS selon le mode d'installation choisi, etc. Je n'ai pas la patience de faire & tester tous ces changements subtils pour des bénéfices mineurs.

Cela dit, libre à vous de modifier la configuration NSIS selon vos besoins spécifiques et de générer un installeur personnel. Bon courage 😃
