### ISSUE TITLE
[Feature Request] Ability to group entries in folders

### ISSUE THREAD

**Issue by Krezzin** [guilryder/clavier-plus#48]
Pretty much self-explanatory, it'd be welcome to be able to group entries in their own folders. Say, for example, you have lots of shortcuts, you'd want to structure them better instead of having them thrown in one big pile of mess. You get my point.

**Comment by guilryder** [comment]
Supporting folders would add a significant amount of complexity for relatively limited benefits. Adding descriptions to shortcuts and sorting by the "Description" column should be good enough in practice.
