### ISSUE TITLE
Holding Ctrl+Alt gets ignored

### ISSUE THREAD

**Issue by wdscxsj** [guilryder/clavier-plus#5]
I'm not sure if this behavior is by design or not, but it's quite different from how Windows Explorer handles global shortcuts. An option to change it will be truly appreciated.

To reproduce:

1. Assign a shortcut `Ctrl+Alt+n` to launch Notepad.
2. Press `Ctrl+Alt+n` once to open a Notepad instance.
3. Still holding `Ctrl+Alt`, press the `n` key repeatedly. This time, no new instances of Notepad are created, but only a series of `n` characters are typed into the first Notepad window.

In contrast, if a global shortcut is assigned to a shortcut of Notepad and thus handled by Explorer, the above keystrokes will create multiple Notepad instances.

**Comment by guilryder** [comment]
This is a known limitation: http://utilfr42.free.fr/util/ClavierDoc.php#limits-repetition

**Comment by wdscxsj** [comment]
@guilryder Thanks for the pointer! I should've read the doc better.
