### ISSUE TITLE
UWP application

### ISSUE THREAD

**Issue by EtianAM** [guilryder/clavier-plus#6]
Can you add options to open an UWP or aplication of store?

**Comment by guilryder** [comment]
Good question! Hopefully yes, but it doesn't look straightforward so I will need to research first.

**Comment by laplaces-entropy** [comment]
I know, I tried to do it, but I can not, thanks for answer.

**Comment by EtianAM** [comment]
Hey!, I find a form... It is possible using some commands with powershell, here is the tutorial I followed, maybe you could do the automatic process in the program:
https://www.addictivetips.com/windows-tips/open-uwp-apps-from-command-line-windows-10/

**Comment by guilryder** [comment]
Starting an app given its ID is indeed not too difficult.

Listing all the available apps with their id, name, and icon so Clavier+ can show them in a menu with their icon is harder.

[Listing the contents of AppsFolder](https://stackoverflow.com/questions/59926644/listing-of-installed-apps-on-windows-10) works, but returns lots of non-UWP apps too. The `System.Link.TargetParsingPath` property seems empty if and only if the app is UWP.

Then combining `SHGetIDListFromObject` + `SHGetFileInfo` allows to retrieve the icon.

I have a working prototype; working on finalizing it.

**Comment by guilryder** [comment]
I have finalized the prototype into a working version, and also fixed a few bugs in the Windows shortcuts resolution involved in Add > Program. I still need to test thoroughly and release the next version.

Beta version binaries:
http://utilfr42.free.fr/dn/beta/ClavierSetup64.exe
http://utilfr42.free.fr/dn/beta/ClavierSetup32.exe
http://utilfr42.free.fr/dn/beta/Clavier64.zip
http://utilfr42.free.fr/dn/beta/Clavier32.zip

**Comment by EtianAM** [comment]
Thanks!
