### ISSUE TITLE
Ctrl + Alt + M ?

### ISSUE THREAD

**Issue by Kev63** [guilryder/clavier-plus#7]
Hi! Just wondering, I updated to the new version of Windows 10 v2004 and Clavier+ to v11.0.0 as well, now the shortcut Ctrl + Alt + M no longer works. Is it normal? Thank you.

Salut ! Je me demandais, j'ai mis à jour Windows 10 en v2004 et Clavier+ en v11.0.0, et depuis le raccourci Ctrl + Alt + M ne fonctionne plus. Est-ce normal ? Merci.

**Comment by guilryder** [comment]
Please refer to the [FAQ](http://utilfr42.free.fr/util/ClavierDoc.php#faq).

**Comment by Kev63** [comment]
Well, it seems you did not answer my question, the Ctrl + Alt + M is the only shortcut that no longer works. I started a new configuration, but when I want to assign keys Ctrl + Alt + M, I can't, the M is not showing up in the box. Every other letters work, but not M, why? Thank you.

**Comment by guilryder** [comment]
FAQ item #1 applied regarding "no longer works".

I cannot reproduce this issue. It looks like a problem specific to your configuration, so I cannot answer your question.
