### ISSUE TITLE
"All programs but" function doesn't work well. 

### ISSUE THREAD

**Issue by VickGE** [guilryder/clavier-plus#8]
I'm using the F1, F2 etc keys to open softwares or do other handy things, but I would like to disable these shortcuts in some software like emulators (Bizhawk by example).

I'm aware of the dropdown "all programs but", and I'm using it, but in a lot of cases it just block the key for the software. It doesn't do the normal key.

So in my case, F1 is doing nothing instead of inputting F1 (AKA loading the first savestate).

**Comment by guilryder** [comment]
It's a limitation with no known solution.

Clavier+ handles "all programs but" by capturing the shortcut for all programs, and simulating the shortcut back if the current program isn't in the list. It requires the current program to be compatible with Clavier+. Emulators and other programs that access the keyboard in a low-level way are [incompatible with Clavier+](http://utilfr42.free.fr/util/ClavierDoc.php#limits-programs).
