### ISSUE TITLE
MouseWheel function does not work properly

### ISSUE THREAD

**Issue by meldarionqeusse** [guilryder/clavier-plus#9]
I am trying to set the [{MouseWheel,-1}] to the UP arrow key and it works meaning it scrolls up. But when I do the same for the down key, meaning [{MouseWheel,+1}] to scroll down this does not work. 

I noticed that only one will work at at time cannot have 2 scroll functions at the same time.

**Comment by guilryder** [comment]
Thanks for reporting this issue. Contrary to what the special commands menu shows, `[{MouseWheel]}` does not support "+" prefixes. You need to write `[{MouseWheel,1]}` instead of `[{MouseWheel,+1]}` to scroll down. The next Clavier+ version will correct the menu item.

**Comment by meldarionqeusse** [comment]
Great works like a charm. Thanks for your help and for the great program
